Repository igraph/rigraph, pull requests merged in 2023-12, with the labels that each got.

#985 chore: Request recent version of cpp11
  DESCRIPTION
Labels: mergequeue, blocked

#979 tests: update based on zzz-deprecate.R
  tests/testthat/test-adjacency.spectral.embedding.R
  tests/testthat/test-attributes.R
  tests/testthat/test-betweenness.R
  tests/testthat/test-bug-154.R
  tests/testthat/test-coloring.R
  tests/testthat/test-correlated.R
  tests/testthat/test-count.multiple.R
  tests/testthat/test-dimSelect.R
  tests/testthat/test-dot.product.game.R
  tests/testthat/test-get.shortest.paths.R
  tests/testthat/test-graph.atlas.R
  tests/testthat/test-hrg.R
  tests/testthat/test-hsbm.R
  tests/testthat/test-identical_graphs.R
  tests/testthat/test-laplacian.spectral.embedding.R
  tests/testthat/test-layout.sugiyama.R
  tests/testthat/test-notable.R
  tests/testthat/test-operators.R
  tests/testthat/test-operators4.R
  tests/testthat/test-rewire.R
  tests/testthat/test-scan.R
  tests/testthat/test-transitivity.R
  tools/deprecate-tests.R
Labels: mergequeue

#980 refactor: manually replace deprecated is.weighted()
  R/scan.R
Labels: mergequeue

#981 refactor: manually replace deprecated is.igraph
  R/scan.R
Labels: mergequeue

#982 refactor: manually replace deprecated graph.neighborhood()
  R/scan.R
Labels: mergequeue

#983 refactor: manually replace graph.strength()
  R/aaa-auto.R
  man/embed_adjacency_matrix.Rd
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#986 refactor: use `is_named()` instead of deprecated `is.named()`
  R/iterators.R
Labels: mergequeue

#987 chore: Work around ggnetwork problems for now
  R/interface.R
Labels: mergequeue

#991 CRAN release v1.6.0
  R/adjacency.R
  cran-comments.md
  revdep/README.md
  revdep/problems.md
  tests/testthat/test-graph.adjacency.R
Labels: CRAN release :station:

#997 chore: Fix Stimulus definitions
  R/aaa-auto.R
  src/vendor/cigraph/interfaces/functions.yaml
  tools/build-requirements.txt
Labels: mergequeue

#999 chore: Avoid deprecated `R_igraph_automorphisms()`
  R/aaa-auto.R
  R/topology.R
  src/cpp11.cpp
  src/rinterface.c
Labels: mergequeue

#1000 fix: Fix compilation on Windows with spaces in the Rtools path
  configure
  src/Makevars.in
  src/Makevars.ucrt
Labels: mergequeue

#1001 refactor: Prepare using lifecycle for deprecations
  R/aaa-a-deprecate.R
  R/adjacency.R
  R/assortativity.R
  R/attributes.R
  R/basic.R
  R/bipartite.R
  R/centrality.R
  R/centralization.R
  R/cliques.R
  R/cohesive.blocks.R
  R/community.R
  R/components.R
  R/console.R
  R/conversion.R
  R/data_frame.R
  R/decomposition.R
  R/degseq.R
  R/demo.R
  R/fit.R
  R/flow.R
  R/foreign.R
  R/games.R
  R/glet.R
  R/hrg.R
  R/incidence.R
  R/interface.R
  R/layout.R
  R/layout_drl.R
  R/make.R
  R/minimum.spanning.tree.R
  R/motifs.R
  R/operators.R
  R/other.R
  R/par.R
  R/paths.R
  R/plot.common.R
  R/plot.shapes.R
  R/scg.R
  R/simple.R
  R/structural.properties.R
  R/structure.info.R
  R/test.R
  R/tkplot.R
  R/topology.R
  R/triangles.R
  R/zzz-deprecate.R
Labels: mergequeue

#1007 refactor: ignore upstream CITATION file to avoid R CMD check NOTE
  .Rbuildignore
  CITATION.cff
Labels: mergequeue

#1021 fix: Intersections between edges and rectangle vertices are computed correctly
  R/plot.shapes.R
  tests/testthat/_snaps/bug-501-rectangles/rectangle-edges.svg
  tests/testthat/test-bug-501-rectangles.R
Labels: mergequeue, blocked

#1013 docs: New `vignette("deprecated-dot-case")` that lists deprecated functions and their alternatives
  DESCRIPTION
  inst/lifecycle/deprecated-table-creation.R
  inst/lifecycle/deprecated.csv
  vignettes/articles/deprecated-dot-case.Rmd
Labels: mergequeue

#1022 chore: Add tools script and template for moving to lifecycle
  tools/deprecate-template.txt
  tools/deprecate.R
Labels: mergequeue

#1030 chore: Regenerate parser
  src/vendor/io/dl-parser.c
Labels: mergequeue-priority, mergequeue

#1033 refactor: Replace loop by `lapply()` when returning vertex and edge sets
  R/aaa-auto.R
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1036 chore: Stabilize `sources.mk`
  rconfigure.py
  src/sources.mk
Labels: mergequeue

#1037 fix: Stimulus argument dependencies
  R/aaa-auto.R
  tools/stimulus/functions-R.yaml
Labels: mergequeue, blocked

#1032 refactor: remove unused parts from code generation
  codecov.yml
  src/rinterface.c
  tools/stimulus/functions-R.yaml
  tools/stimulus/types-RC.yaml
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1035 feat: Use `[]` assignment for converting matrices
  R/aaa-auto.R
  R/centrality.R
  R/games.R
  R/layout.R
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1031 refactor: clean up some auto-generation code
  R/aaa-auto.R
  tools/stimulus/types-RC.yaml
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1038 chore: Use new function in favor of deprecated one
  R/hrg.R
Labels: mergequeue

#1041 chore: Avoid deprecated function
  R/scg.R
Labels: mergequeue-priority, mergequeue

#1043 chore: Move towards autogenerating all bindings
  R/aaa-auto.R
  src/cpp11.cpp
  src/rinterface.c
  tools/stimulus/functions-R.yaml
  tools/sync-yaml.R
Labels: mergequeue-priority, mergequeue

#1048 chore: Don't pass attributes to C functions
  R/aaa-auto.R
  src/cpp11.cpp
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1049 refactor: remove unused stimulus type VERTEXSETLIST_INT
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1052 refactor/type-refactorings
  R/aaa-auto.R
  R/structural.properties.R
  src/rinterface.c
  src/rinterface_extra.c
  tests/testthat/test-reciprocity.R
  tools/build-requirements.txt
  tools/stimulus/functions-R.yaml
  tools/stimulus/types-RC.yaml
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1055 refactor: do not duplicate prototypes, use a common header for rinterface.c / rinterface_extra.c
  src/rinterface.c
  src/rinterface.h
  src/rinterface_extra.c
  tools/stimulus/rinterface.c.in
Labels: mergequeue

#1028 feat: New `k_shortest_paths()` to compute the first k shortest paths between two vertices
  NAMESPACE
  R/aaa-auto.R
  R/igraph-package.R
  R/structural.properties.R
  man/bfs.Rd
  man/components.Rd
  man/constraint.Rd
  man/coreness.Rd
  man/degree.Rd
  man/dfs.Rd
  man/distances.Rd
  man/edge_density.Rd
  man/ego.Rd
  man/feedback_arc_set.Rd
  man/girth.Rd
  man/is_acyclic.Rd
  man/is_dag.Rd
  man/k_shortest_paths.Rd
  man/knn.Rd
  man/laplacian_matrix.Rd
  man/matching.Rd
  man/reciprocity.Rd
  man/subcomponent.Rd
  man/subgraph.Rd
  man/topo_sort.Rd
  man/transitivity.Rd
  man/unfold_tree.Rd
  man/which_multiple.Rd
  man/which_mutual.Rd
  src/rinterface.c
  tests/testthat/test-k_shortest_paths.R
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1060 chore: Remove unused types
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1062 feat!: Remove `NA` padding for `dfs(unreachable = FALSE)$order` and `$order.out` and for `bfs(unreachable = FALSE)$order` .
  R/structural.properties.R
  revdep/cran.md
  tests/testthat/_snaps/graph.bfs.md
  tests/testthat/test-graph.bfs.R
  tests/testthat/test-graph.dfs.R
Labels: mergequeue
