Repository igraph/rigraph, pull requests merged in 2024-10, with the labels that each got.

#1541 test: test-cliques
  tests/testthat/helper-unvs.R
  tests/testthat/test-all.st.cuts.R
  tests/testthat/test-bug-1073800-clique.R
  tests/testthat/test-cliques.R
  tests/testthat/test-graphlets.R
  tests/testthat/test-independent.vertex.sets.R
  tests/testthat/test-largest.independent.vertex.sets.R
  tests/testthat/test-maximal_cliques.R
  tests/testthat/test-structural.properties.R
  tests/testthat/test-weighted_cliques.R
Labels: upkeep, mergequeue

#1520 test: add tests for `graph_from_biadjacency_matrix()`
  R/incidence.R
  tests/testthat/_snaps/incidence.md
  tests/testthat/test-incidence.R
Labels: mergequeue

#1543 lifecycle: Deprecate `eigen_centrality(scale = )`
  R/centrality.R
  man/eigen_centrality.Rd
  man/evcent.Rd
  tests/testthat/_snaps/centrality.md
  tests/testthat/test-alpha.centrality.R
  tests/testthat/test-arpack.R
  tests/testthat/test-centrality.R
  tests/testthat/test-evcent.R
  tests/testthat/test-graph.eigen.R
Labels: mergequeue

#1549 fix: put deprecation message at the beginning not the end of the similarity functions
  R/similarity.R
Labels: mergequeue

#1547 chore: document {devtag} in contributing guide
  .github/CONTRIBUTING.md
  DESCRIPTION
Labels: mergequeue

#1536 fix: preserve `as.undirected()` signature thanks to @jhollway
  R/conversion.R
  man/as.undirected.Rd
Labels: mergequeue

#1537 docs: groom NEWS file
  NEWS.md
Labels: mergequeue

#1552 docs: update allcontributors table
  README.md
Labels: mergequeue

#1554 test: deprecated graph_()
  tests/testthat/test-isomorphism.R
  tests/testthat/test-make.R
  tests/testthat/test-make_graph.R
Labels: mergequeue

#1553 feat: more {cli}
  R/adjacency.R
  R/attributes.R
  R/bipartite.R
  R/centrality.R
  R/community.R
  R/conversion.R
  R/data_frame.R
  R/demo.R
  R/games.R
  R/incidence.R
  R/iterators.R
  R/layout.R
  R/make.R
  R/operators.R
  R/other.R
  R/palette.R
  R/print.R
  R/scan.R
  R/structural.properties.R
  R/versions.R
  tests/testthat/_snaps/versions.md
  tests/testthat/test-make_lattice.R
Labels: mergequeue

#1556 Prepare for libxml2 depending on bcrypt, use pkg-config.
  src/Makevars.ucrt
Labels: mergequeue

#1557 fix: Account for functions in iterators
  R/iterators.R
Labels: mergequeue

#1546 feat: Add `p.value` and `p.precision` arguments to `fit_power_law()` to control the computation of the p-value
  .gitignore
  R/fit.R
  man/fit_power_law.Rd
  src/cpp11.cpp
  src/rinterface_extra.c
  tests/testthat/test-fit.R
Labels: mergequeue

#1558 CRAN release v2.1.1
  .Rbuildignore
  CITATION.cff
  DESCRIPTION
  NEWS.md
  README.md
  cran-comments.md
Labels: CRAN release :station:
