Repository igraph/rigraph, pull requests merged in 2024-01, with the labels that each got.

#1057 fix: local (weighted) transitivity now produces a named vector
  R/structural.properties.R
  tests/testthat/test-transitivity.R
Labels: mergequeue

#1051 fix: check that we receive a scalar when expecting a scalar in C code
  revdep/README.md
  revdep/cran.md
  revdep/failures.md
  revdep/problems.md
  src/rinterface.c
  src/rinterface.h
  src/rinterface_extra.c
  tools/stimulus/types-RC.yaml
Labels: mergequeue

#1064 chore: Standardize the handling of some stimulus enum types
  R/aaa-auto.R
  R/community.R
  R/components.R
  R/conversion.R
  R/foreign.R
  R/structural.properties.R
  src/cpp11.cpp
  src/rinterface.c
  src/rinterface_extra.c
  tools/stimulus/types-RC.yaml
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1067 refactor!: remove graph.isomorphic.34(), fixes #1065
  NAMESPACE
  R/topology.R
Labels: mergequeue

#1069 fix: add scalar conversion checks in a few critical places
  src/rinterface_extra.c
  tests/testthat/test-make_graph.R
Labels: mergequeue

#1066 Check that matrix sizes are in the supported range before passing them to R
  src/rinterface.h
  src/rinterface_extra.c
Labels: mergequeue

#1070 refactor: remove unused vectorlist / matrixlist destructors
  src/rinterface.h
  src/rinterface_extra.c
Labels: mergequeue

#1078 fix: Restore `hrg_tree()` semantics
  R/hrg.R
  man/hrg_tree.Rd
Labels: mergequeue

#1084 docs: rm get.adjacency() usage from intro vignettes
  vignettes/igraph.Rmd
  vignettes/igraph_ES.rmd
Labels: mergequeue

#1087 chore: Reduce warnings from `R CMD check`
  R/aaa-auto.R
  tools/stimulus/igraph_export.h
Labels: mergequeue

#1089 fix: path to vendor header files
  Makefile-cigraph
  src/vendor/igraph_export.h
  tools/stimulus/igraph_export.h
Labels: mergequeue

#1072 feat!: `as_adjacency_matrix()` no longer supports attributes of type `character`
  R/conversion.R
  revdep/README.md
  revdep/cran.md
  revdep/problems.md
Labels: mergequeue

#1093 fix: temporary remove functions with sparse matrices
  R/aaa-auto.R
  src/cpp11.cpp
  src/rinterface.c
  src/rinterface.h
  src/rinterface_extra.c
Labels: mergequeue

#1092 Fixes for Makevars.in for unix (revert accidental file updates)
  src/Makevars.in
Labels: mergequeue

#1099 chore: Remove roxygen2 warnings
  R/igraph-package.R
  R/printr.R
  R/utils.R
  _pkgdown.yml
  man/aaa-igraph-package.Rd
  man/printr.Rd
Labels: mergequeue-priority, mergequeue

#1117 docs: rm stray alias
  R/make.R
  man/make_bipartite_graph.Rd
Labels: mergequeue

#1012 ci: go back to stricter checks
  .github/workflows/build-and-check.yml
  R/aaa-auto.R
  R/structural.properties.R
  configure
  man/k_shortest_paths.Rd
  src/Makevars.in
  src/cpp11.cpp
  src/rinterface.c
  src/rinterface_extra.c
  src/vendor/cigraph/include/igraph_error.h
  tools/stimulus/types-RC.yaml
Labels: mergequeue

#1114 feat!: remove default value for 'loops' argument of centr_degree_tmax()
  R/centralization.R
  man/centr_degree_tmax.Rd
Labels: mergequeue

#1104 refactor!: change R/par.R
  R/par.R
  man/getIgraphOpt.Rd
  man/igraph.options.Rd
  man/igraph_options.Rd
Labels: mergequeue

#1085 test: remove top-level code in test-indexing.R
  tests/testthat/helper-indexing.R
  tests/testthat/test-indexing.R
  tests/testthat/test-indexing2.R
Labels: mergequeue

#1112 refactor: use %||% from rlang
  NAMESPACE
  R/igraph-package.R
  R/utils.R
Labels: mergequeue

#1075 fix: remove `R_SEXP_to_hrg` use `R_SEXP_to_hrg_copy` to avoid memory leak
  src/rinterface.c
  src/rinterface_extra.c
  tools/stimulus/types-RC.yaml
Labels: mergequeue

#1101 feat!: `get.edge.ids(multi = TRUE)` is no longer supported
  R/interface.R
  man/get.edge.ids.Rd
Labels: mergequeue

#1124 fix: `bfs()` no longer pads `order` with zeros with `igraph_options(return.vs.es = FALSE)`
  R/interface.R
  R/structural.properties.R
  man/get.edge.ids.Rd
  tests/testthat/test-graph.bfs.R
  tests/testthat/test-graph.dfs.R
  tests/testthat/test-graphNEL.R
Labels: mergequeue

#1080 chore!: Hard-deprecate `as_adjacency_matrix(edges = )`
  R/conversion.R
  man/as_adjacency_matrix.Rd
  man/get.adjacency.Rd
  revdep/README.md
  revdep/cran.md
  revdep/failures.md
  revdep/problems.md
  tests/testthat/test-indexing.R
Labels: mergequeue

#1127 tests: unskip all `is_tree()` tests
  tests/testthat/test-trees.R
Labels: mergequeue

#1128 test: prevent `decompose()` test from being reported as skipped
  tests/testthat/test-decompose.graph.R
Labels: mergequeue

#1129 chore: Update vendored igraph/C to igraph/igraph@fb82a46e36cf9bf4851b6d17a58e4653b8769ad5
  src/vendor/cigraph/src/layout/large_graph.c
Labels: mergequeue

#1130 chore: Update vendored igraph/C to igraph/igraph@9de3ecdf0097ba01f6cc5f8ef5a6a58e6cf984a4
  src/vendor/cigraph/src/layout/fruchterman_reingold.c
  src/vendor/cigraph/src/layout/layout_random.c
Labels: mergequeue

#1149 test: use specific skip() function
  tests/testthat/test-graphNEL.R
Labels: mergequeue

#1119 docs: improve Edge connectivity docs
  R/flow.R
  man/edge_connectivity.Rd
  man/vertex_connectivity.Rd
Labels: mergequeue

#1153 docs: Add description for `normalized` argument to `assortativity()`
  R/assortativity.R
  man/assortativity.Rd
  man/assortativity.nominal.Rd
Labels: mergequeue

#1154 test: split as_biadjacency_matrix() tests
  tests/testthat/test-get.incidence.R
Labels: mergequeue-priority, mergequeue

#1155 test: Add `as_biadjacency_matrix()` tests for named vectors
  tests/testthat/test-get.incidence.R
Labels: mergequeue

#1160 CRAN release v2.0.0
  R/aaa-auto.R
  R/community.R
  R/interface.R
  R/layout_drl.R
  R/scg.R
  cran-comments.md
  man/as_membership.Rd
  man/cluster_edge_betweenness.Rd
  man/cluster_fast_greedy.Rd
  man/cluster_fluid_communities.Rd
  man/cluster_infomap.Rd
  man/cluster_label_prop.Rd
  man/cluster_leading_eigen.Rd
  man/cluster_leiden.Rd
  man/cluster_louvain.Rd
  man/cluster_optimal.Rd
  man/cluster_spinglass.Rd
  man/cluster_walktrap.Rd
  man/communities.Rd
  man/compare.Rd
  man/groups.Rd
  man/make_clusters.Rd
  man/modularity.igraph.Rd
  man/plot_dendrogram.communities.Rd
  man/split_join_distance.Rd
  src/Makevars.in
  src/cpp11.cpp
Labels: CRAN release :station:

#1163 Add test
  R/cpp11.R
  R/plot.shapes.R
  src/cpp11.cpp
  src/simpleraytracer.cpp
  src/sources.mk
  tests/testthat/_snaps/plot/basic-graph-spheres.svg
  tests/testthat/test-plot.R
Labels: mergequeue

#1151 docs: improve docs of assortativity
  R/assortativity.R
  man/assortativity.Rd
Labels: mergequeue

#1164 CRAN release v2.0.1
  CITATION.cff
  DESCRIPTION
  NEWS.md
  R/layout.R
  cran-comments.md
  man/layout_with_graphopt.Rd
Labels: CRAN release :station:

#1171 fix: HAVE_GFORTRAN flag for `win` and `ucrt`
  src/Makevars.ucrt
  src/Makevars.win
Labels: mergequeue

#1152 refactor: add read-only comments for RStudio IDE
  R/aaa-auto.R
  src/rinterface.c
  tools/stimulus/aaa-auto.R.in
  tools/stimulus/rinterface.c.in
Labels: mergequeue

#1179 fix: Remove zeros from the `order` and `order.out` components returned by `dfs()`
  R/structural.properties.R
  tests/testthat/test-graph.dfs.R
Labels: mergequeue
