Repository igraph/rigraph, pull requests merged in 2024-02, with the labels that each got.

#1184 docs: improve installation and troubleshooting instructions
  README.md
  vignettes/articles/installation-troubleshooting.Rmd
Labels: mergequeue

#1185 fix: eliminate a compiler warning from simpleraytracer
  src/simpleraytracer.cpp
Labels: mergequeue

#1186 feat: `distances()` now supports the Floyd-Warshall algorithm
  R/structural.properties.R
  man/distances.Rd
  src/rinterface_extra.c
  tests/testthat/test-distances.R
Labels: mergequeue

#1191 docs: Fix typo in `?articulation_points`
  R/components.R
  man/articulation_points.Rd
Labels: mergequeue

#1196 fix: memory leaks when converting data to C
  src/rinterface.c
  tools/stimulus/types-RC.yaml
Labels: mergequeue

#1167 docs: remove scg related docs
  R/stochastic_matrix.R
  R/structural.properties.R
  _pkgdown.yml
  man/bfs.Rd
  man/components.Rd
  man/constraint.Rd
  man/coreness.Rd
  man/degree.Rd
  man/dfs.Rd
  man/distances.Rd
  man/edge_density.Rd
  man/ego.Rd
  man/feedback_arc_set.Rd
  man/get.stochastic.Rd
  man/girth.Rd
  man/is_acyclic.Rd
  man/is_dag.Rd
  man/k_shortest_paths.Rd
  man/knn.Rd
  man/laplacian_matrix.Rd
  man/matching.Rd
  man/reciprocity.Rd
  man/scg-method.Rd
  man/stochastic_matrix.Rd
  man/subcomponent.Rd
  man/subgraph.Rd
  man/topo_sort.Rd
  man/transitivity.Rd
  man/unfold_tree.Rd
  man/which_multiple.Rd
  man/which_mutual.Rd
Labels: mergequeue

#1166 test: set seed *locally*
  tests/testthat/test-adjacency.spectral.embedding.R
  tests/testthat/test-authority.score.R
  tests/testthat/test-ba.game.R
  tests/testthat/test-bipartite.projection.R
  tests/testthat/test-bipartite.random.game.R
  tests/testthat/test-cliques.R
  tests/testthat/test-clusters.R
  tests/testthat/test-communities.R
  tests/testthat/test-constraint.R
  tests/testthat/test-constructor-modifiers.R
  tests/testthat/test-contract.vertices.R
  tests/testthat/test-convex_hull.R
  tests/testthat/test-correlated.R
  tests/testthat/test-dimSelect.R
  tests/testthat/test-dot.product.game.R
  tests/testthat/test-fastgreedy.community.R
  tests/testthat/test-forestfire.R
  tests/testthat/test-graph.edgelist.R
  tests/testthat/test-graph.eigen.R
  tests/testthat/test-graph.knn.R
  tests/testthat/test-graph.subisomorphic.lad.R
  tests/testthat/test-graph.subisomorphic.vf2.R
  tests/testthat/test-graphlets.R
  tests/testthat/test-hrg.R
  tests/testthat/test-hsbm.R
  tests/testthat/test-is.bipartite.R
  tests/testthat/test-label.propagation.community.R
  tests/testthat/test-laplacian.spectral.embedding.R
  tests/testthat/test-layout.fr.R
  tests/testthat/test-layout.kk.R
  tests/testthat/test-layout.mds.R
  tests/testthat/test-layout.merge.R
  tests/testthat/test-leading.eigenvector.community.R
  tests/testthat/test-leiden.R
  tests/testthat/test-maximal_cliques.R
  tests/testthat/test-motifs.R
  tests/testthat/test-multilevel.community.R
  tests/testthat/test-operators4.R
  tests/testthat/test-optimal.community.R
  tests/testthat/test-print.R
  tests/testthat/test-random_walk.R
  tests/testthat/test-sample.R
  tests/testthat/test-scan.R
  tests/testthat/test-sgm.R
  tests/testthat/test-sir.R
  tests/testthat/test-sphere.R
  tests/testthat/test-transitivity.R
  tests/testthat/test-vs-es-printing.R
  tests/testthat/test-walktrap.community.R
Labels: mergequeue

#1198 chore: Update vendored igraph/C to igraph/igraph@8def9e335ae1cbb98150…
  src/vendor/cigraph/.all-contributorsrc
  src/vendor/cigraph/.pre-commit-config.yaml
  src/vendor/cigraph/CHANGELOG.md
  src/vendor/cigraph/CONTRIBUTORS.md
  src/vendor/cigraph/CONTRIBUTORS.txt
  src/vendor/cigraph/include/igraph_components.h
  src/vendor/cigraph/include/igraph_constructors.h
  src/vendor/cigraph/include/igraph_interface.h
  src/vendor/cigraph/include/igraph_types.h
  src/vendor/cigraph/interfaces/functions.yaml
  src/vendor/cigraph/src/CMakeLists.txt
  src/vendor/cigraph/src/centrality/hub_authority.c
  src/vendor/cigraph/src/connectivity/components.c
  src/vendor/cigraph/src/constructors/atlas.c
  src/vendor/cigraph/src/constructors/prufer.c
  src/vendor/cigraph/src/core/grid.c
  src/vendor/cigraph/src/games/sbm.c
  src/vendor/cigraph/src/graph/caching.c
  src/vendor/cigraph/src/graph/visitors.c
  src/vendor/cigraph/src/hrg/hrg_types.cc
  src/vendor/cigraph/src/io/graphml.c
  src/vendor/cigraph/src/io/pajek-lexer.l
  src/vendor/cigraph/src/layout/drl/DensityGrid.cpp
  src/vendor/cigraph/src/layout/drl/DensityGrid.h
  src/vendor/cigraph/src/layout/drl/DensityGrid_3d.cpp
  src/vendor/cigraph/src/layout/drl/DensityGrid_3d.h
  src/vendor/cigraph/src/layout/drl/drl_graph.cpp
  src/vendor/cigraph/src/layout/drl/drl_graph_3d.cpp
  src/vendor/cigraph/src/layout/drl/drl_layout.cpp
  src/vendor/cigraph/src/layout/drl/drl_layout_3d.cpp
  src/vendor/cigraph/src/layout/drl/drl_parse.h
  src/vendor/cigraph/src/misc/bipartite.c
  src/vendor/cigraph/src/misc/cocitation.c
  src/vendor/cigraph/src/misc/degree_sequence.cpp
  src/vendor/cigraph/src/paths/bellman_ford.c
  src/vendor/cigraph/src/paths/dijkstra.c
  src/vendor/cigraph/src/paths/unweighted.c
  src/vendor/cigraph/src/properties/dag.c
Labels: mergequeue

#1205 fix: workaround for deprecated enum values not being supported with old GCC
  src/vendor/igraph_config.h
Labels: mergequeue

#1201 docs: improved docs for shortest path functions
  R/structural.properties.R
  man/distances.Rd
Labels: mergequeue

#1209 docs: update troubleshooting document, emphasize issues with Anaconda environments
  DESCRIPTION
  man/greedy_vertex_coloring.Rd
  vignettes/articles/installation-troubleshooting.Rmd
Labels: mergequeue

#1207 refactor: eliminate manual edits from autogenerated files
  R/aaa-auto.R
  src/cpp11.cpp
  src/rinterface.c
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1215 fix: Link Fortran runtime on Windows as needed by arpack.
  src/Makevars.ucrt
Labels: mergequeue

#1216 chore: `config.h` defines `HAVE___UINT128_T`
  src/vendor/config.h
Labels: mergequeue

#1197 fix: `configure` manage libxml multiple include paths
  configure
Labels: mergequeue

#1210 chore: update stimulus to 0.21.4
  tools/build-requirements.txt
Labels: mergequeue

#1204 feat: `is_biconnected()` checks if a graph is biconnected
  NAMESPACE
  R/components.R
  man/articulation_points.Rd
  man/biconnected_components.Rd
  man/components.Rd
  man/decompose.Rd
  man/is_biconnected.Rd
  tests/testthat/test-biconnected.components.R
Labels: mergequeue

#1068 refactor: make_empty_graph() is now fully auto-generated
  R/aaa-auto.R
  R/make.R
  src/cpp11.cpp
  src/rinterface.c
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1213 fix: `biconnected_components()` now returns edge and vertex sequences again
  R/components.R
  tests/testthat/test-biconnected.components.R
Labels: mergequeue

#1212 feat: `realize_bipartite_degseq()` creates a bipartite graph from two degree sequences
  NAMESPACE
  R/aaa-auto.R
  R/make.R
  _pkgdown.yml
  man/realize_bipartite_degseq.Rd
  man/realize_degseq.Rd
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1219 fix: `isomorphisms()` and `subgraph_isomorphisims(method = "vf2")` work again, regression introduced in 2.0.0
  R/topology.R
Labels: mergequeue

#1223 fix: Avoid duplicate objects
  R/aaa-auto.R
  R/components.R
  R/lazyeval.R
  R/structural.properties.R
Labels: mergequeue

#1222 fix: `shortest.paths()` no longer fails
  R/structural.properties.R
  revdep/README.md
  revdep/cran.md
  revdep/failures.md
  revdep/problems.md
Labels: mergequeue

#1228 docs: recommend {pak} instead of {remotes}
  README.md
Labels: mergequeue

#1226 fix: `sample_pa()` respects the `out.seq` and `out.dist` arguments again, regression introduced in igraph 2.0.0
  src/rinterface_extra.c
  tests/testthat/test-ba.game.R
Labels: mergequeue

#1232 fix: do not rely on `which` program during configuration
  configure
  src/Makevars.in
Labels: mergequeue

#1234 chore: remove unused patch files
  patches/001-fix-cxsparse-include.patch
  patches/002-workaround-gml-creator.patch
Labels: mergequeue

#1233 refactor: always use bundled mini-gmp
  DESCRIPTION
  src/Makevars.in
  src/Makevars.ucrt
  src/Makevars.win
  src/vendor/config.h
Labels: mergequeue

#1235 refactor: remove empty string in configure
  configure
Labels: mergequeue

#1243 docs: formatting tweaks in introductory vignettes
  vignettes/igraph.Rmd
  vignettes/igraph_ES.rmd
Labels: documentation, mergequeue

#1237 chore: update C core and regenerate interfaces
  R/aaa-auto.R
  src/rinterface.c
  src/vendor/cigraph/CHANGELOG.md
  src/vendor/cigraph/interfaces/functions.yaml
  src/vendor/cigraph/src/centrality/truss.cpp
  src/vendor/cigraph/src/graph/basic_query.c
  src/vendor/cigraph/src/graph/type_indexededgelist.c
  src/vendor/cigraph/src/paths/all_shortest_paths.c
  src/vendor/cigraph/src/paths/sparsifier.c
  src/vendor/cigraph/src/properties/trees.c
Labels: mergequeue

#1236 Update build-requirements.txt
  tools/build-requirements.txt
Labels: mergequeue, stimulus, hackathon-topic :calendar:

#1247 fix: `g + vertices(1, 2, foo = 3)` works again, regression introduced in igraph 2.0.0
  DESCRIPTION
  R/operators.R
  tests/testthat/_snaps/operators.md
  tests/testthat/test-operators.R
Labels: mergequeue

#1251 CRAN release v2.0.2
  CITATION.cff
  DESCRIPTION
  NEWS.md
  cran-comments.md
Labels: CRAN release :station:

#1230 docs: split is_bipartite() manual page from other manual page
  R/attributes.R
  R/make.R
  man/bipartite_mapping.Rd
  man/bipartite_projection.Rd
  man/is.bipartite.Rd
  man/is_bipartite.Rd
  man/make_bipartite_graph.Rd
Labels: mergequeue

#1173 feat: New `voronoi_cells()` to compute the Voronoi partitioning of a graph
  NAMESPACE
  R/aaa-auto.R
  R/community.R
  man/as_membership.Rd
  man/cluster_edge_betweenness.Rd
  man/cluster_fast_greedy.Rd
  man/cluster_fluid_communities.Rd
  man/cluster_infomap.Rd
  man/cluster_label_prop.Rd
  man/cluster_leading_eigen.Rd
  man/cluster_leiden.Rd
  man/cluster_louvain.Rd
  man/cluster_optimal.Rd
  man/cluster_spinglass.Rd
  man/cluster_walktrap.Rd
  man/communities.Rd
  man/compare.Rd
  man/groups.Rd
  man/make_clusters.Rd
  man/modularity.igraph.Rd
  man/plot_dendrogram.communities.Rd
  man/split_join_distance.Rd
  man/voronoi_cells.Rd
  tests/testthat/test-voronoi.R
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1254 refactor: auto-generate `are_adjacent()`, avoid deprecated `igraph_are_connected()` C function
  R/aaa-auto.R
  R/structure.info.R
  man/are_adjacent.Rd
  src/cpp11.cpp
  src/rinterface.c
  src/rinterface_extra.c
  src/vendor/cigraph/CHANGELOG.md
  src/vendor/cigraph/include/igraph_community.h
  src/vendor/cigraph/include/igraph_structural.h
  src/vendor/cigraph/interfaces/functions.yaml
  src/vendor/cigraph/src/CMakeLists.txt
  src/vendor/cigraph/src/community/edge_betweenness.c
  src/vendor/cigraph/src/connectivity/separators.c
  src/vendor/cigraph/src/core/sparsemat.c
  src/vendor/cigraph/src/flow/flow.c
  src/vendor/cigraph/src/graph/basic_query.c
  src/vendor/cigraph/src/io/dl.c
  src/vendor/cigraph/src/io/gml.c
  src/vendor/cigraph/src/io/lgl.c
  src/vendor/cigraph/src/io/ncol.c
  src/vendor/cigraph/src/io/pajek.c
  src/vendor/cigraph/src/misc/matching.c
  src/vendor/cigraph/src/operators/compose.c
  src/vendor/cigraph/src/operators/disjoint_union.c
  src/vendor/cigraph/src/operators/rewire.c
  src/vendor/cigraph/src/operators/subgraph.c
  src/vendor/cigraph/src/paths/sparsifier.c
  tests/testthat/test-are_adjacent.R
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1256 docs: GMP is no longer a dependency
  README.md
  vignettes/articles/installation-troubleshooting.Rmd
Labels: mergequeue

#1252 docs: Fix error messages mentioning to mention `upgrade_graph()` instead of the nonexisting `upgrade_version()`
  src/rinterface_extra.c
  tests/testthat/_snaps/old-data-type.md
  tests/testthat/_snaps/versions.md
Labels: mergequeue

#1263 docs: remove incorrect claim about handling of complete graphs by `is_separator()` and `is_min_separator()`
  R/flow.R
  man/is_min_separator.Rd
  man/is_separator.Rd
Labels: mergequeue

#1156 Source files for vendored libraries
  DESCRIPTION
  configure
  rconfigure.py
  src/Makevars.in
  src/Makevars.ucrt
  src/Makevars.win
  src/sources.mk
  src/vendor/cigraph/vendor/glpk/sources-glpk.mk
  src/vendor/cigraph/vendor/mini-gmp/sources-mini-gmp.mk
  src/vendor/mini-gmp/mini-gmp.c
  src/vendor/mini-gmp/mini-gmp.h
Labels: mergequeue

#1268 docs: rm duplicate seealso from sample_pa.Rd
  R/games.R
  man/sample_pa.Rd
Labels: mergequeue

#1270 docs: add code finding duplicate seealso, and use it
  R/components.R
  R/games.R
  R/iterators.R
  R/operators.R
  R/plot.R
  man/articulation_points.Rd
  man/edge.Rd
  man/igraph-es-attributes.Rd
  man/rep.igraph.Rd
  man/reverse_edges.Rd
  man/rglplot.Rd
  man/sample_bipartite.Rd
  man/sample_degseq.Rd
  man/sample_gnm.Rd
  man/sample_gnp.Rd
  man/sample_grg.Rd
  man/sample_growing.Rd
  man/sample_pa_age.Rd
  man/sample_smallworld.Rd
  man/vertex.Rd
  tools/find-duplicate-seealso.R
Labels: documentation, mergequeue
