Repository igraph/rigraph, pull requests merged in 2024-06, with the labels that each got.

#1015 Rename resolution_parameter to resolution
  R/community.R
  man/cluster_leiden.Rd
  tests/testthat/test-leiden.R
Labels: lifecycle

#1370 Refactoring around adjacency.R
  R/adjacency.R
  tests/testthat/_snaps/adjacency.md
  tests/testthat/test-adjacency.R
  tests/testthat/test-bug-1019624.R
  tests/testthat/test-graph.adjacency.R
Labels: mergequeue

#1393 fix: `sample_degseq()` works with old method names again
  R/games.R
  tests/testthat/test-games.R
Labels: mergequeue

#1390 refactor!: change make.R
  NAMESPACE
  R/aaa-a-deprecate.R
  R/make.R
  man/graph.Rd
  man/graph.atlas.Rd
  man/graph.bipartite.Rd
  man/graph.de.bruijn.Rd
  man/graph.empty.Rd
  man/graph.extended.chordal.ring.Rd
  man/graph.famous.Rd
  man/graph.formula.Rd
  man/graph.full.Rd
  man/graph.full.bipartite.Rd
  man/graph.full.citation.Rd
  man/graph.kautz.Rd
  man/graph.lattice.Rd
  man/graph.lcf.Rd
  man/graph.ring.Rd
  man/graph.star.Rd
  man/graph.tree.Rd
  man/graph_from_atlas.Rd
  man/graph_from_lcf.Rd
  man/graph_from_literal.Rd
  man/line.graph.Rd
  man/make_bipartite_graph.Rd
  man/make_chordal_ring.Rd
  man/make_de_bruijn_graph.Rd
  man/make_empty_graph.Rd
  man/make_full_bipartite_graph.Rd
  man/make_full_citation_graph.Rd
  man/make_full_graph.Rd
  man/make_graph.Rd
  man/make_kautz_graph.Rd
  man/make_lattice.Rd
  man/make_line_graph.Rd
  man/make_ring.Rd
  man/make_star.Rd
  man/make_tree.Rd
  tools/deprecate-make-template.txt
  tools/deprecate-make.R
Labels: mergequeue

#1395 refactor: expect_that(is_equivalent())
  tests/testthat/test-authority.score.R
  tests/testthat/test-bipartite.projection.R
  tests/testthat/test-contract.vertices.R
  tests/testthat/test-dot.product.game.R
  tests/testthat/test-get.adjlist.R
  tests/testthat/test-get.incidence.R
  tests/testthat/test-graph.bipartite.R
  tests/testthat/test-graph.data.frame.R
  tests/testthat/test-hrg.R
  tests/testthat/test-indexing.R
  tests/testthat/test-operators4.R
  tools/expect_equal.R
Labels: mergequeue

#1402 chore: Infrastructure to review revdepcheck results
  .Rbuildignore
  R/revdep.R
  revdep/.gitignore
Labels: mergequeue

#1406 fix: Put back header files for consumption by Bison
  Makefile-cigraph
Labels: mergequeue, blocked

#1407 ci: try installing {graph} again
  .github/workflows/build-and-check.yml
Labels: mergequeue

#1408 test: stop using prints_text() in test-bipartite.random.game.R
  tests/testthat/test-bipartite.random.game.R
  tests/testthat/test-edge.betweenness.community.R
  tests/testthat/test-fastgreedy.community.R
  tests/testthat/test-print.R
  tests/testthat/test-walktrap.community.R
Labels: mergequeue

#1412 test: remove expect_that() definition
  tests/testthat/helper.R
Labels: mergequeue

#1397 refactor: use `lifecycle::deprecated()` now that we can
  R/community.R
  R/conversion.R
  R/interface.R
  man/as_adjacency_matrix.Rd
  man/cluster_leiden.Rd
  man/get.edge.ids.Rd
Labels: upkeep, lifecycle, mergequeue, hackathon-topic :calendar:

#1398 chore!: Hard-deprecate `get.edge()` and `layout.grid.3d()` which have been deprecated for 10 years
  R/basic.R
  R/interface.R
  R/layout.R
  man/ends.Rd
  man/get.edge.Rd
  man/layout.grid.3d.Rd
  man/layout_on_grid.Rd
Labels: upkeep, lifecycle, mergequeue, hackathon-topic :calendar:

#1399 refactor: use lifecycle in R/iterators.R
  R/iterators.R
  tests/testthat/test-deprecated_indexing_functions.R
Labels: mergequeue, hackathon-topic :calendar:

#1413 docs: Fix typos in `?plot.common` (@gvegayon)
  man/plot.common.Rd
Labels: mergequeue

#1368 More auto-generation
  R/aaa-auto.R
  R/games.R
  R/structural.properties.R
  man/sample_growing.Rd
  src/rinterface.c
  src/rinterface_extra.c
  tools/stimulus/functions-R.yaml
Labels: mergequeue

#1416 feat: `sample_chung_lu()`
  NAMESPACE
  R/aaa-auto.R
  R/games.R
  man/erdos.renyi.game.Rd
  man/sample_.Rd
  man/sample_bipartite.Rd
  man/sample_chung_lu.Rd
  man/sample_correlated_gnp.Rd
  man/sample_correlated_gnp_pair.Rd
  man/sample_degseq.Rd
  man/sample_dot_product.Rd
  man/sample_fitness.Rd
  man/sample_fitness_pl.Rd
  man/sample_forestfire.Rd
  man/sample_gnm.Rd
  man/sample_gnp.Rd
  man/sample_grg.Rd
  man/sample_growing.Rd
  man/sample_hierarchical_sbm.Rd
  man/sample_islands.Rd
  man/sample_k_regular.Rd
  man/sample_last_cit.Rd
  man/sample_pa.Rd
  man/sample_pa_age.Rd
  man/sample_pref.Rd
  man/sample_sbm.Rd
  man/sample_smallworld.Rd
  man/sample_traits_callaway.Rd
  man/sample_tree.Rd
  src/cpp11.cpp
  src/rinterface.c
  tests/testthat/test-chung_lu.R
  tools/stimulus/functions-R.yaml
  tools/stimulus/types-RR.yaml
Labels: mergequeue
