Repository igraph/rigraph, pull requests merged in 2024-04, with the labels that each got.

#1335 ci: install R
  .github/workflows/build-and-check.yml
Labels: mergequeue-priority, mergequeue

#1326 refactor: explaining variables
  R/attributes.R
Labels: upkeep, mergequeue

#1336 refactor: move variables closer to their usage, add explaining variables
  R/attributes.R
Labels: upkeep, mergequeue

#1339 chore: Use and explain `getNamespaceInfo()`
  R/test.R
Labels: mergequeue

#1310 ci: run examples with comment `\dontrun{}`
  tools/run_examples.R
Labels: mergequeue

#1342 refactor: handle `null` names for `R_igraph_mybracket2_names`
  src/rinterface_extra.c
Labels: mergequeue
