Repository igraph/rigraph, pull requests merged in 2024-11, with the labels that each got.

#1568 fix: fix the incorrect handling of the `sample` parameter in `sample_motifs()` and ensure that the default `sample.size` is integer
  R/motifs.R
  man/graph.motifs.est.Rd
  man/sample_motifs.Rd
  tests/testthat/test-motifs.R
  tests/testthat/test-plot.R
Labels: mergequeue, blocked

#1578 ci: Work around rgl sanitizer failure
  .github/workflows/build-and-check.yml
  tests/testthat/test-plot.R
Labels: mergequeue

#1575 chore: Configure the RStudio IDE to use the extra roclets
  igraph.Rproj
Labels: mergequeue

#1579 ci: Install rgl from GitHub for Sanitizer runs
  .github/workflows/build-and-check.yml
  tests/testthat/test-plot.R
Labels: mergequeue

#1591 fledge: CRAN pre-release v2.1.1.9900
  DESCRIPTION
  NEWS.md
  cran-comments.md
Labels: CRAN release :station:
