Repository igraph/rigraph, pull requests merged in 2024-09, with the labels that each got.

#1474 feat!: remove tkigraph from {igraph} proper
  NAMESPACE
  R/socnet.R
  R/tkigraph.R
  _pkgdown.yml
  inst/html_library.license.terms
  inst/html_library.tcl
  inst/igraph.gif
  inst/igraph2.gif
  inst/my_html_library.tcl
  inst/tkigraph_help/communities.html
  inst/tkigraph_help/index.html
  inst/tkigraph_help/style.css
  inst/tkigraph_help/tkigraph-main.gif
  man/tkigraph.Rd
Labels: mergequeue, hackathon-topic :calendar:

#1487 fix: add ellipsis to dummy functions `.nei()` and others
  R/iterators.R
  man/inside-square-error.Rd
Labels: mergequeue

#1484 docs: add a custom roxygen2 cdocs tag
  DESCRIPTION
  R/make.R
  man/make_empty_graph.Rd
Labels: mergequeue

#1490 chore: increase cpp11 minimal version
  DESCRIPTION
Labels: mergequeue

#1500 chore: properly deprecate some functions in layout.R
  R/layout.R
  _pkgdown.yml
  man/layout.circle.Rd
  man/layout.deprecated.Rd
  man/layout.fruchterman.reingold.Rd
  man/layout.fruchterman.reingold.grid.Rd
  man/layout.kamada.kawai.Rd
  man/layout.lgl.Rd
  man/layout.random.Rd
  man/layout.reingold.tilford.Rd
  man/layout.sphere.Rd
  man/layout.spring.Rd
  man/layout.svd.Rd
Labels: lifecycle, mergequeue

#1498 chore: use lifecycle for deprecation of membership argument of modula…
  R/community.R
  man/modularity.igraph.Rd
  tests/testthat/_snaps/modularity_matrix.md
  tests/testthat/test-modularity_matrix.R
Labels: lifecycle, mergequeue

#1493 chore: soft-deprecate `graph_()`
  R/make.R
Labels: mergequeue

#1494 chore: replace `is.directed()` with `is_directed()` in stimulus YAML
  R/aaa-auto.R
  tools/stimulus/types-RR.yaml
Labels: mergequeue

#1504 test: refactor test-layout.fr.R for simplicity and readability
  R/layout.R
  man/layout_with_fr.Rd
  man/layout_with_kk.Rd
  tests/testthat/_snaps/layout.md
  tests/testthat/test-layout.R
  tests/testthat/test-layout.fr.R
  tests/testthat/test-layout.kk.R
  tests/testthat/test-layout.mds.R
  tests/testthat/test-layout.merge.R
  tests/testthat/test-layout.sugiyama.R
  tests/testthat/test-layout_nicely.R
  tests/testthat/test-layout_null_singleton.R
  tests/testthat/test-new-layout-api.R
Labels: mergequeue

#1506 chore: Results from revdepcheck
  revdep/README.md
  revdep/cran.md
  revdep/failures.md
  revdep/problems.md
Labels: mergequeue

#1505 lifecycle and tests in structural.properties
  R/structural.properties.R
  man/bfs.Rd
  man/dfs.Rd
  man/graph.bfs.Rd
  man/graph.dfs.Rd
  tests/testthat/_snaps/structural.properties.md
  tests/testthat/test-components.R
  tests/testthat/test-constraint.R
  tests/testthat/test-degree.R
  tests/testthat/test-diameter.R
  tests/testthat/test-distances.R
  tests/testthat/test-farthest_vertices.R
  tests/testthat/test-get.all.shortest.paths.R
  tests/testthat/test-get.diameter.R
  tests/testthat/test-get.shortest.paths.R
  tests/testthat/test-girth.R
  tests/testthat/test-graph.bfs.R
  tests/testthat/test-graph.coreness.R
  tests/testthat/test-graph.dfs.R
  tests/testthat/test-k_shortest_paths.R
  tests/testthat/test-matching.R
  tests/testthat/test-neighborhood.R
  tests/testthat/test-structural.properties.R
  tests/testthat/test-transitivity.R
  tests/testthat/test-unfold.tree.R
Labels: mergequeue

#1509 lifecycle: `erdos.renyi.game()` and `random.graph.game()` soft deprecation
  R/games.R
  man/erdos.renyi.game.Rd
  tests/testthat/test-adjacency.spectral.embedding.R
  tests/testthat/test-correlated.R
  tests/testthat/test-laplacian.spectral.embedding.R
  tests/testthat/test-scan.R
  tests/testthat/test-sgm.R
Labels: lifecycle, mergequeue

#1510 feat: create get_edge_ids() as new name for get.edge.ids()
  NAMESPACE
  R/indexing.R
  R/interface.R
  R/iterators.R
  man/adjacent_vertices.Rd
  man/are_adjacent.Rd
  man/delete_edges.Rd
  man/ends.Rd
  man/get.edge.ids.Rd
  man/get_edge_ids.Rd
  man/gorder.Rd
  man/gsize.Rd
  man/head_of.Rd
  man/incident.Rd
  man/incident_edges.Rd
  man/is_directed.Rd
  man/neighbors.Rd
  man/sub-.igraph.Rd
  man/sub-sub-.igraph.Rd
  man/tail_of.Rd
  tests/testthat/_snaps/interface.md
  tests/testthat/test-interface.R
  vignettes/igraph.Rmd
  vignettes/igraph_ES.rmd
Labels: lifecycle, mergequeue

#1507 docs: use {devtag} for internal function docs
  .Rbuildignore
  DESCRIPTION
  R/make.R
  R/other.R
  man/dot-apply_modifiers.Rd
  man/dot-extract_constructor_and_modifiers.Rd
Labels: documentation, mergequeue

#1515 chore: formally deprecate `similarity.<something>()` functions
  R/similarity.R
  man/similarity.Rd
  man/similarity.dice.Rd
  man/similarity.invlogweighted.Rd
  man/similarity.jaccard.Rd
Labels: lifecycle, mergequeue

#1516 chore: make `.igraph.progress()` and `.igraph.status()` more internal
  .Rbuildignore
  NAMESPACE
  R/console.R
  man/console.Rd
  man/dot-igraph.progress.Rd
  man/dot-igraph.status.Rd
Labels: lifecycle, mergequeue

#1512 chore: start deprecate `graph.edges()` to `graph_from_edges()`
  NAMESPACE
  R/structural.properties.R
  R/trees.R
  man/sample_spanning_tree.Rd
  man/subgraph.Rd
  man/subgraph.edges.Rd
  tests/testthat/_snaps/trees.md
  tests/testthat/test-trees.R
Labels: lifecycle, mergequeue

#1517 chore: Update vendored sources to igraph/igraph@1f153e9ca1b7e03ae4387d2500b4ccf4d3bc2703
  src/vendor/cigraph/CHANGELOG.md
  src/vendor/cigraph/src/layout/large_graph.c
  src/vendor/igraph_version.h
Labels: mergequeue

#1530 chore: use %||% in R/fit.R
  R/epi.R
  R/fit.R
Labels: upkeep, mergequeue

#1529 CRAN release v2.1.0
  CITATION.cff
  DESCRIPTION
  NEWS.md
  R/basic.R
  R/centrality.R
  R/cliques.R
  R/community.R
  R/conversion.R
  R/games.R
  R/interface.R
  R/iterators.R
  R/layout.R
  R/make.R
  R/palette.R
  R/similarity.R
  R/structural.properties.R
  cran-comments.md
  man/diverging_pal.Rd
  man/dot-apply_modifiers.Rd
  man/dot-extract_constructor_and_modifiers.Rd
  man/dot-igraph.progress.Rd
  man/dot-igraph.status.Rd
  man/handle_vertex_type_arg.Rd
  man/layout_in_circle.Rd
  man/sequential_pal.Rd
  tests/testthat/test-bug-501-rectangles.R
  tests/testthat/test-plot.R
Labels: CRAN release :station:

#1538 docs: use mathjax for now
  _pkgdown.yml
Labels: documentation, mergequeue

#1519 test: add tests for as_adjacency_matrix() in test-conversion
  tests/testthat/_snaps/conversion.md
  tests/testthat/test-conversion.R
Labels: upkeep, mergequeue, blocked
