Repository igraph/rigraph, pull requests merged in 2024-03, with the labels that each got.

#1267 fix: Fix `rglplot(edge_label = )`
  R/plot.R
  tests/testthat/test-plot.R
Labels: mergequeue

#1275 chore: Move `.mk` files to root to fix vendoring
  src/Makevars.in
  src/Makevars.ucrt
  src/Makevars.win
  src/mkfile.plan9
  src/sources-glpk.mk
  src/sources-mini-gmp.mk
Labels: mergequeue

#1278 chore: Fix drift after code generation
  Makefile-cigraph
  rconfigure.py
  src/Makevars.in
  src/Makevars.ucrt
  src/Makevars.win
  src/sources-glpk.mk
  src/sources.mk
  src/vendor/io/dl-parser.c
  src/vendor/io/gml-parser.c
  src/vendor/io/lgl-parser.c
  src/vendor/io/ncol-parser.c
  src/vendor/io/pajek-lexer.c
  src/vendor/io/pajek-parser.c
  src/vendor/io/parsers/dl-parser.h
  src/vendor/io/parsers/gml-parser.h
  src/vendor/io/parsers/lgl-parser.h
  src/vendor/io/parsers/ncol-parser.h
  src/vendor/io/parsers/pajek-parser.h
  tools/stimulus/igraph_export.h
Labels: mergequeue

#1276 chore: Model vendoring after duckdb
  Makefile-cigraph
  src/vendor/igraph_version.h
  tools/update-cigraph.sh
Labels: mergequeue

#1280 docs: add logo
  .gitignore
  README.md
  man/figures/logo.png
  pkgdown/favicon/apple-touch-icon-120x120.png
  pkgdown/favicon/apple-touch-icon-152x152.png
  pkgdown/favicon/apple-touch-icon-180x180.png
  pkgdown/favicon/apple-touch-icon-60x60.png
  pkgdown/favicon/apple-touch-icon-76x76.png
  pkgdown/favicon/apple-touch-icon.png
  pkgdown/favicon/favicon-16x16.png
  pkgdown/favicon/favicon-32x32.png
  pkgdown/favicon/favicon.ico
Labels: mergequeue

#1279 docs: add link to discussion forum
  _pkgdown.yml
Labels: mergequeue

#1264 docs: Improve `min_st_separators()` documentation
  R/flow.R
  man/min_st_separators.Rd
  tests/testthat/_snaps/minimal.st.separators.md
  tests/testthat/test-minimal.st.separators.R
Labels: mergequeue

#1282 chore: make libxml optional
  DESCRIPTION
  configure
  src/Makevars.ucrt
  src/Makevars.win
  src/vendor/config.h
Labels: mergequeue

#1288 ci: run examples with sanitizer
  .github/workflows/build-and-check.yml
  tools/run_examples.R
Labels: mergequeue

#1291 refactor: replace use of deprecated barabasi.game() with sample_pa()
  R/socnet.R
Labels: mergequeue

#1294 docs: remove misleading comment about warning given as no warning is given
  R/centrality.R
  man/strength.Rd
Labels: mergequeue

#1301 docs: make `x11()` usage in example happen only in interactive sessions
  R/conversion.R
  man/as.directed.Rd
Labels: mergequeue

#1304 chore: Install lock workflow to lock stale discussions after one year
  .github/workflows/lock.yaml
Labels: mergequeue

#1305 CRAN release v2.0.3
  CITATION.cff
  DESCRIPTION
  NEWS.md
  cran-comments.md
Labels: CRAN release :station:

#1309 ci: Update lock.yaml
  .github/workflows/lock.yaml
Labels: mergequeue

#1314 ci: remove running examples in sanitizer
  .github/workflows/build-and-check.yml
Labels: mergequeue

#1313 docs: Update `igraph.Rmd`, fix manual page typo
  vignettes/igraph.Rmd
Labels: mergequeue

#1306 test: Add skip condition for `rglplot` test
  tests/testthat/test-plot.R
Labels: mergequeue

#1307 docs: replace `\dontrun{}` with `@examplesIf`
  R/conversion.R
  R/games.R
  R/hrg.R
  man/as_graphnel.Rd
  man/fit_hrg.Rd
  man/graph_from_graphnel.Rd
  man/predict_edges.Rd
  man/sample_pref.Rd
Labels: mergequeue

#1302 docs: fix `graph_from_adjacency_matrix()` examples to avoid warnings
  R/adjacency.R
  man/graph_from_adjacency_matrix.Rd
Labels: documentation, mergequeue

#1297 docs: fix `sample_degseq()` example
  R/games.R
  man/sample_degseq.Rd
Labels: mergequeue

#1320 refactor: early return() in graph_attr()
  R/attributes.R
Labels: mergequeue

#1318 sample_forestfire() tests and example :fire:
  R/games.R
  man/sample_forestfire.Rd
  tests/testthat/test-forestfire.R
Labels: mergequeue

#1323 test: use largest_component() and expect_equal() in test files
  tests/testthat/test-clusters.R
  tests/testthat/test-degseq.R
  tests/testthat/test-diameter.R
  tests/testthat/test-edge.connectivity.R
Labels: mergequeue

#1322 refactor: add assert_named_list() helper to assert the value is a named list with no duplicate names
  R/attributes.R
  tests/testthat/test-attributes.R
Labels: upkeep, mergequeue
