Repository igraph/rigraph, pull requests merged in 2024-05, with the labels that each got.

#1315 test: improve sample_degseq() tests
  tests/testthat/_snaps/games.md
  tests/testthat/test-degseq.R
  tests/testthat/test-games.R
Labels: mergequeue

#1357 fix: comment failing ci
  .github/workflows/build-and-check.yml
  src/rinterface_extra.c
Labels: mergequeue

#1366 test: Refactoring around `interface.R`
  tests/testthat/helper.R
  tests/testthat/test-add.edges.R
  tests/testthat/test-add.vertices.R
  tests/testthat/test-as.directed.R
  tests/testthat/test-ba.game.R
  tests/testthat/test-bipartite.projection.R
  tests/testthat/test-delete.edges.R
  tests/testthat/test-delete.vertices.R
  tests/testthat/test-get.adjacency.R
  tests/testthat/test-get.adjlist.R
  tests/testthat/test-get.edge.R
  tests/testthat/test-get.edgelist.R
  tests/testthat/test-graph.adjlist.R
  tests/testthat/test-graph.atlas.R
  tests/testthat/test-graph.complementer.R
  tests/testthat/test-graph.compose.R
  tests/testthat/test-graph.de.bruijn.R
  tests/testthat/test-graph.edgelist.R
  tests/testthat/test-graphNEL.R
  tests/testthat/test-interface.R
  tests/testthat/test-neighborhood.R
  tests/testthat/test-neighbors.R
  tests/testthat/test-operators.R
  tests/testthat/test-operators3.R
  tests/testthat/test-sbm.game.R
  tests/testthat/test-unfold.tree.R
Labels: mergequeue

#1343 fix `%\>%` typo in vignettes
  vignettes/igraph.Rmd
  vignettes/igraph_ES.rmd
Labels: mergequeue

#1367 fix: fixed potential memory leak in `R_igraph_community_to_membership2()`
  src/rinterface_extra.c
Labels: mergequeue

#1374 ci: Work around installation problems for the graph package
  .github/workflows/build-and-check.yml
  DESCRIPTION
Labels: mergequeue

#1347 fix: fix reading of LGL and NCOL files (broken in 2.0.0)
  R/foreign.R
  tests/testthat/test-read_graph.R
Labels: mergequeue

#1371 test: refactor test-assortativity for readability
  tests/testthat/test-assortativity.R
Labels: upkeep, mergequeue

#1372 Refactoring around test-attributes.R
  tests/testthat/test-attributes.R
  tests/testthat/test-is.bipartite.R
Labels: mergequeue

#1376 feat: rename sample_degseq() method and add the edge.switching.simple method
  R/games.R
  R/make.R
  man/degree.sequence.game.Rd
  man/make_.Rd
  man/sample_degseq.Rd
  tests/testthat/test-games.R
Labels: mergequeue

#1381 test: Improve attribute tests
  tests/testthat/test-operators.R
Labels: mergequeue

#1382 fix: add missing `PROTECT`
  src/rinterface_extra.c
Labels: mergequeue, blocked
