Repository igraph/rigraph, pull requests merged in 2025-07, with the labels that each got.

#1899 feat: add `plot(vertex.label.angle = , vertex.label.adj = )` arguments to rotate vertex labels
  R/plot.R
  R/plot.common.R
  man/plot.common.Rd
  tests/testthat/_snaps/plot/label-rotate.svg
  tests/testthat/test-plot.R
Labels: plotting :chart:, hackathon-topic :calendar:

#1898 feat: added `plot(mark.lwd = )` to change line width of mark.groups
  R/plot.R
  man/plot.igraph.Rd
  tests/testthat/_snaps/plot/mark-border-lwd.svg
  tests/testthat/test-plot.R
Labels: plotting :chart:, hackathon-topic :calendar:

#1881 fix: automatically arrange loops in `plot()`
  R/plot.R
  R/plot.common.R
  man/plot.common.Rd
  tests/testthat/_snaps/plot/basic-graph-layout-1.svg
  tests/testthat/_snaps/plot/basic-graph-layout-2.svg
  tests/testthat/_snaps/plot/basic-graph-spheres.svg
  tests/testthat/_snaps/plot/loop-graph.svg
  tests/testthat/_snaps/plot/multi-loops-many.svg
  tests/testthat/_snaps/plot/multi-loops-triangle.svg
  tests/testthat/test-plot.R
Labels: plotting :chart:

#1879 fix: HRG printing with `type = "auto"` uses `"plain"` for large trees
  R/hrg.R
  R/iterators.R
  tests/testthat/_snaps/hrg.md
  tests/testthat/test-hrg.R
Labels: hackathon-topic :calendar:

#1915 refactor: Improve logic for updating edge attributes
  R/attributes.R
  tests/testthat/test-attributes.R
Labels: hackathon-topic :calendar:

#1982 feat: added weights parameter to `local_scan()`
  R/scan.R
  man/local_scan.Rd
  tests/testthat/helper-indexing.R
  tests/testthat/test-scan.R
Labels: hackathon-topic :calendar:
